create extension if not exists pgcrypto;
create table if not exists couples(id uuid primary key default gen_random_uuid(),created_at timestamptz default now(),partner_a_name text not null,partner_b_name text not null,invite_token text unique not null,partner_a_completed boolean default false,partner_b_completed boolean default false,paid boolean default false);
create table if not exists answers(id bigint generated by default as identity primary key,couple_id uuid references couples(id) on delete cascade,role text check(role in ('a','b')),question_id text not null,answer_value text,created_at timestamptz default now(),unique(couple_id,role,question_id));
create table if not exists reports(id uuid primary key default gen_random_uuid(),couple_id uuid unique references couples(id) on delete cascade,report_json jsonb not null,generated_at timestamptz default now());
create table if not exists payments(id bigint generated by default as identity primary key,payment_id text unique not null,couple_id uuid references couples(id) on delete cascade,amount numeric,status text,created_at timestamptz default now());
alter table couples enable row level security;alter table answers enable row level security;alter table reports enable row level security;alter table payments enable row level security;


